pool:
  name: myadoagent
  #imageName: ubuntu-18.04

trigger: none
pr: none

steps:
- checkout: none
- bash: |
    docker --version
    docker pull alpine
  displayName: 'docker'
- bash: az version   
  displayName: 'az'
- bash: terraform version   
  displayName: 'terraform'
- bash: helm version   
  displayName: 'helm'
